### ISSUE TITLE
Python 3 error with --demangle

### ISSUE THREAD

**Issue by letmaik** [eriwen/lcov-to-cobertura-xml#24]
When I use `--demangle` I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/lcov_cobertura", line 9, in <module>
    load_entry_point('lcov-cobertura==1.6', 'console_scripts', 'lcov_cobertura')()
  File "/usr/local/lib/python3.4/dist-packages/lcov_cobertura.py", line 407, in main
    cobertura_xml = lcov_cobertura.convert()
  File "/usr/local/lib/python3.4/dist-packages/lcov_cobertura.py", line 86, in convert
    return self.generate_cobertura_xml(coverage_data)
  File "/usr/local/lib/python3.4/dist-packages/lcov_cobertura.py", line 282, in generate_cobertura_xml
    'name': self.format(method_name),
  File "/usr/local/lib/python3.4/dist-packages/lcov_cobertura.py", line 38, in demangle
    self.pipe.stdin.write(name + "\n")
TypeError: 'str' does not support the buffer interface
```

I installed the latest master version via `pip install git+https://github.com/eriwen/lcov-to-cobertura-xml.git`

**Comment by eriwen** [comment]
This should be fixed now. Please try with the latest v2.0.1 release and let me know if this is still an issue.
